matrix:
  include:
    # Job 1) Analyze the code
    - os: linux
      jdk: oraclejdk8
      sudo: false
      addons:
        apt:
          # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
          sources:
            - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
            - llvm-toolchain-precise # for clang-format-5.0
          packages:
            - libstdc++6
            - fonts-droid
      before_script:
        - git clone https://github.com/flutter/flutter.git --depth 1 $HOME/flutter
        - export PATH=$HOME/flutter/bin:$HOME/flutter/bin/cache/dart-sdk/bin:$PATH
        - flutter doctor
        - flutter packages get
      script:
        - flutter analyze
    # Job 2) Check format and run tests
    - os: linux
      jdk: oraclejdk8
      sudo: false
      addons:
        apt:
          # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
          sources:
            - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
            - llvm-toolchain-precise # for clang-format-5.0
          packages:
            - libstdc++6
            - fonts-droid
            - clang-format-5.0
      before_script:
        - git clone https://github.com/flutter/flutter.git --depth 1 $HOME/flutter
        - export PATH=$HOME/flutter/bin:$HOME/flutter/bin/cache/dart-sdk/bin:$PATH
        - flutter doctor
      script:
        - ./scripts/format_code.sh
    # Job 3) Build example APKs and run Java tests
    - os: linux
      jdk: oraclejdk8
      sudo: false
      addons:
        apt:
          # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
          sources:
            - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
          packages:
            - lib32stdc++6 # https://github.com/flutter/flutter/issues/6207
            - libstdc++6
            - fonts-droid
      before_script:
        - git clone https://github.com/flutter/flutter.git --depth 1 $HOME/flutter
        - export PATH=$HOME/flutter/bin:$HOME/flutter/bin/cache/dart-sdk/bin:$PATH
        - wget https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip
        - mkdir $HOME/android-sdk
        - unzip -qq sdk-tools-linux-3859397.zip -d $HOME/android-sdk
        - export ANDROID_HOME=$HOME/android-sdk
        - export PATH=$HOME/android-sdk/tools/bin:$PATH
        - mkdir -p /home/travis/.android # silence sdkmanager warning
        - echo 'count=0' > /home/travis/.android/repositories.cfg # silence sdkmanager warning
        - echo y | sdkmanager "tools"
        - echo y | sdkmanager "platform-tools"
        - echo y | sdkmanager "build-tools;25.0.3"
        - echo y | sdkmanager "platforms;android-25"
        - echo y | sdkmanager "extras;android;m2repository"
        - echo y | sdkmanager "extras;google;m2repository"
        - echo y | sdkmanager "patcher;v4"
        - sdkmanager --list
        - wget http://services.gradle.org/distributions/gradle-3.5-bin.zip
        - mkdir $HOME/gradle-3.5
        - unzip -qq gradle-3.5-bin.zip -d $HOME/gradle-3.5
        - export GRADLE_HOME=$HOME/gradle-3.5
        - export PATH=$GRADLE_HOME/bin:$PATH
        - gradle -v
        - flutter doctor
      script:
        - flutter build apk
    # Job 4) Build example IPAs
    - os: osx
      language: generic
      osx_image: xcode9.3
      before_script:
        - pip2 install six
        - brew update
        - brew install libimobiledevice
        - brew install ideviceinstaller
        - brew install ios-deploy
        - git clone https://github.com/flutter/flutter.git --depth 1 $HOME/flutter
        - export PATH=$HOME/flutter/bin:$HOME/flutter/bin/cache/dart-sdk/bin:$PATH
      script:
        - flutter build ios --no-codesign
cache:
  directories:
    - $HOME/.pub-cache
