name: permission_handler
description: Permission plugin for Flutter. This plugin provides a cross-platform (iOS, Android) API to request and check permissions.
version: 4.3.0
homepage: https://github.com/baseflowit/flutter-permission-handler

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.1.6

dev_dependencies:
  effective_dart: ^1.2.1

flutter:
  plugin:
    androidPackage: com.baseflow.permissionhandler
    pluginClass: PermissionHandlerPlugin
